#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-storage-benchmark"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "493cd998c8fb440ab008bf13a095255e"

[[d1_databases]]
binding = "DB"
database_name = "d1"
database_id = "98232c46-ea95-4631-8d5d-2770a36a44ac"

[[r2_buckets]]
binding = 'R2'
bucket_name = 'cloudflare-storage-benchmark-r2'


